
server:
  port: 9200
spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:mysql://localhost/cryptolog?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  queries:
    users-query: select email, password, '1' as enabled from auth_user where email=? and verified='true'
    roles-query: select u.email, r.role_name from auth_user u inner join auth_user_role ur on(u.auth_user_id=ur.auth_user_id) inner join auth_role r on(ur.auth_role_id=r.auth_role_id) where u.email=?
security:
  basic:
    enabled: false

assets:
  maximalist: Maximalist
  conservative: Conservative
  gambler: Gambler
  custom: Custom

messages:
  token:
    nf: token not found
    ac: alreadyconfirmed
    ex: expired
    co: confirmed
  email:
    sender: cryptolog.404@gmail.com
    loginFail:
      warningTitle: CryptoLog Warning
      warningText: Someone is trying to log in on your CryptoLog account!
    verification:
      encoding: "utf-8"
      link: "http://localhost:9200/confirm?token="
      datePattern: "yyyy-MM-dd HH:mm"
      confirmTitle: Confirm your email
      confirmText: "Please confirm your email by clicking on the following link: http://localhost:9200/confirm?token="
      failed: Failed to send email
  user:
    userRole:
      name: "SITE_USER"
      description: "This user has access to site, after login - normal user"
  asset:
    emptyPortfolio: "Missing coins. Please mind that you need to continue adding coins to your portfolio in order to select an asset allocation."
    maximalistInfo: "Please mind that The Maximalist portfolio allocation only takes into account Bitcoin. If you have multiple coins in your portfolio, these will be ignored for any yield calculation"
    missingCoinsConserv: "Missing coin from Tier 2. Please mind that you need to continue adding coins to your portfolio in order to select this particular asset allocation"
    missingCoinsGambler: "Missing coin from Tier 2 or 3. Please mind that you need to continue adding coins to your portfolio in order to select this particular asset allocation"
    customError: "Please make sure all your coins add up to 100%"
    customSuccess: "You have successfully customized your the asset allocation in your portfolio. Go to the yield calculator and see how much you could potentially save by investing in crypto."
