server:
  port: 9200
spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:mysql://localhost/cryptolog?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

security:
  basic:
    enabled: false

assets:
  maximalist: Maximalist
  conservative: Conservative
  gambler: Gambler
  custom: Custom

messages:
  token:
    nf: token not found
    ac: alreadyconfirmed
    ex: expired
    co: confirmed
  email:
    sender: cryptolog.404@gmail.com
    loginFail:
      warningTitle: CryptoLog Warning
      warningText: Someone is trying to log in on your CryptoLog account!
    verification:
      encoding: "utf-8"
      link: "http://localhost:9200/confirm?token="
      datePattern: "yyyy-MM-dd HH:mm"
      confirmTitle: Confirm your email
      confirmText: "Please confirm your email by clicking on the following link: "
      confirmRequestURL: "/confirm?token="
      failed: Failed to send email
  user:
    userRole:
      name: "SITE_USER"
      description: "This user has access to site, after login - normal user"
      assetsAllocation: "none"
  asset:
    title: "assetMessage"
    successMessage: "You have successfully set the Asset Allocation in your portfolio. Go to the yield calculator and see how much you could potentially save by investing in crypto."
    emptyPortfolio: "Missing coins! Please mind that you need to continue adding coins to your portfolio in order to select an asset allocation."
    maximalistInfo: "Successfully set Asset Allocation. Please mind that The Maximalist portfolio allocation only takes into account Bitcoin. If you have multiple coins in your portfolio, these will be ignored for any yield calculation."
    missingCoinsConserv: "Missing coin from Tier 2 or Tier 3! Please mind that you need to continue adding coins to your portfolio in order to select this particular asset allocation."
    missingTierOneConserv: "Missing coin from Tier 1! Please mind that you need to continue adding coins to your portfolio in order to select this particular asset allocation."
    missingCoinsGambler: "Missing coin from Tier 2 or 3! Please mind that you need to continue adding coins to your portfolio in order to select this particular asset allocation."
    missingTierOneGambler: "Missing coin from Tier 1! Please mind that you need to continue adding coins to your portfolio in order to select this particular asset allocation."
    customError: "Please make sure all your coins add up to 100%!"
    customSuccess: "You have successfully customized the Asset Allocation in your portfolio. Go to the yield calculator and see how much you could potentially save by investing in crypto."

  passwordService:
    u: user
    title: message
    er: error
    emId: emailId
    resetPw: resetPassword2
    successRPw: successResetPassword
    forgotPw: forgotPassword
    successFPw: successForgotPassword
    resetSubject: "Complete Password Reset!"
    resetRequestReceived: "To complete the password reset process, please click here: "
    resetRequestURL: "/confirm-reset?token="
    resetCheckInbox: "Request to reset password received. Check your inbox for the reset link. Please also check your Spam folder!"
    resetSuccessfully: "Password successfully reset. You can now log in with the new credentials."
    mailNotExists: "This email does not exist!"
    brokenLink: "The link is invalid or broken!"

  registration:
    rightFormat: "Please write the fields in the right format!"
    registeredButNotVerified: "Account already registered, but the Email is NOT VERIFIED! Please proceed to the login page in order to validate your email."
    registeredForEmail: "There is already an account registered with CryptoLog for this email!"
    proceedToLogin: "Please proceed to log in!"
    regSuccessVerifyEmail: "User is registered successfully, please verify your email! Please also check your Spam folder!"

  yieldcalculator:
   noprofile: "You have to select a profile in order to make the calculations."

  verification:
    display:
      name: "user"
      viewName: "verification"
    resendEmail:
      name: "message"
      successText: "Verification link successfully resent. Please also check your Spam folder!"
      vnSuccess: "verificationSuccess"
      errorText: "This email does not exist!"
      vnError: "error"

  login:
    incorrectPassword: "Your email or password is incorrect. Please try again!"
    emailNotValidated: "Your email is not validated! Resend <a href=\"/verification\">Verification Link</a>?"
    getLoggedIn:
      badCred: Bad credentials
      errMess: errorMessage
      disabled: User is disabled
      login: login

  portfolioBalance:
