server:
  port: 9200
spring:
  datasource:
    url: jdbc:mysql://localhost/cryptolog?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: cryptolog.404@gmail.com
    password: kyudwennokkhytll
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    protocol: smtp
    test-connection: false

    from:
     email: cryptolog.404@gmail.com

  queries:
    users-query: select email, password, '1' as enabled from auth_user where email=? and verified='true'
    roles-query: select u.email, r.role_name from auth_user u inner join auth_user_role ur on(u.auth_user_id=ur.auth_user_id) inner join auth_role r on(ur.auth_role_id=r.auth_role_id) where u.email=?
security:
  basic:
    enabled: false

messages:
  token:
    nf: token not found
    ac: alreadyconfirmed
    ex: expired
    co: confirmed
  email:
    sender: cryptolog.404@gmail.com
    loginFail:
      warningTitle: CryptoLog Warning
      warningText: Someone is trying to log in on your CryptoLog account!
    verification:
      encoding: "utf-8"
      link: "http://localhost:9200/confirm?token="
      datePattern: "yyyy-MM-dd HH:mm"
      confirmTitle: Confirm your email
      confirmText: "Please confirm your email by clicking on the following link: http://localhost:9200/confirm?token="
      failed: Failed to send email
  user:
    userRole:
      name: "SITE_USER"
      description: "This user has access to site, after login - normal user"
    yieldRole:
      name: "YIELD_USER"
      description: "This user has access to calculator fields"
